version: "3.9"
services:
  parser-service:
    build:
      context: ./parser-service
    ports:
      - "5555:5555"

  backend-service:
    build:
      context: ./backend-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  user-interface:
    build:
      context: ./user-interface
    ports:
      - "3000:3000"
    depends_on:
      - backend-service
      - parser-service

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
