name: Build and Deploy to GitHub Pages with Dependencies

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start dependencies
        run: |
          docker-compose up -d parser-service backend-service
          # Wait for services to be healthy
          docker-compose run --rm wait-for-it backend-service:8080 -t 60
          docker-compose run --rm wait-for-it parser-service:5555 -t 60

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./user-interface

      - name: Build and export Next.js app
        run: |
          npm run build
          npm run export
        working-directory: ./user-interface

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          publish_dir: ./user-interface/out

      - name: Stop and clean up Docker services
        if: always()
        run: docker-compose down
