name: Kitchen Assistant

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: alpine-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Flask image
        uses: docker/build-push-action@v4
        with:
          context: ./parser-service
          push: true
          tags: tyreesamurai/parser-service:latest

      - name: Build & push Go image
        uses: docker/build-push-action@v4
        with:
          context: ./backend-service
          push: true
          tags: tyreesamurai/backend-service:latest

      - name: Build & push Next.js image
        uses: docker/build-push-action@v4
        with:
          context: ./user-interface
          push: true
          tags: tyreesamurai/user-interface:latest

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v5
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: next
