name: Kitchen Assistant

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Flask image
        uses: docker/build-push-action@v4
        with:
          context: ./parser-service
          push: true
          tags: tyreesamurai/parser-service:latest

      - name: Build & push Go image
        uses: docker/build-push-action@v4
        with:
          context: ./backend-service
          push: true
          tags: tyreesamurai/backend-service:latest

      - name: Build & push Next.js image
        uses: docker/build-push-action@v4
        with:
          context: ./user-interface
          push: true
          tags: tyreesamurai/user-interface:latest

      - name: Deploy to GitHub Pages
        if: success()
        run: echo "Deploying UI to GitHub Pages ..."
