name: Kitchen Assistant

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build and push Docker images
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Flask image
        uses: docker/build-push-action@v4
        with:
          context: ./parser-service
          push: true
          tags: tyreesamurai/parser-service:latest

      - name: Build & push Go image
        uses: docker/build-push-action@v4
        with:
          context: ./backend-service
          push: true
          tags: tyreesamurai/backend-service:latest

      - name: Build & push Next.js image
        uses: docker/build-push-action@v4
        with:
          context: ./user-interface
          push: true
          tags: tyreesamurai/user-interface:latest

      - name: Extract static files from Next.js image
        run: |
          docker create --name nextjs-build tyreesamurai/user-interface:latest
          docker cp nextjs-build:/usr/src/app/out ./out
          docker rm nextjs-build

      - name: Upload Next.js build artifact
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: ./out

  # Deploy the built Next.js app to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: build # Ensures this job runs after the build job
    steps:
      - name: Download Next.js build artifact
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: ./out
